
include_guard()

if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    set(CMAKE_CXX_FLAGS_DEBUG "${ARCHI_FLAG} ${STL_DEBUG_FLAGS} -ggdb3 -O0 ${RTTI_FLAGS}" CACHE STRING "" FORCE)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    set(CMAKE_CXX_FLAGS_DEBUG "${ARCHI_FLAG} ${STL_DEBUG_FLAGS} -ggdb3 -O0 ${RTTI_FLAGS}" CACHE STRING "" FORCE)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Intel")
    set(CMAKE_CXX_FLAGS_DEBUG "${ARCHI_FLAG} -g3 -O0 ${RTTI_FLAGS}" CACHE STRING "" FORCE)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
    set(CMAKE_CXX_FLAGS_DEBUG "${ARCHI_FLAG} /Z7 /Od ${RTTI_FLAGS}" CACHE STRING "" FORCE)
endif()

mark_as_advanced(CMAKE_CXX_FLAGS_DEBUG)
