
include_guard()

mark_as_advanced(CMAKE_CXX_FLAGS_DEBUG)

if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    set(CMAKE_CXX_FLAGS_DEBUG "${ARCHI_FLAG} -ggdb3 -O0" CACHE STRING "" FORCE)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    set(CMAKE_CXX_FLAGS_DEBUG "${ARCHI_FLAG} -ggdb3 -O0" CACHE STRING "" FORCE)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Intel")
    set(CMAKE_CXX_FLAGS_DEBUG "${ARCHI_FLAG} -g3 -O0" CACHE STRING "" FORCE)
elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
    set(CMAKE_CXX_FLAGS_DEBUG "${ARCHI_FLAG} /Z7 /Od" CACHE STRING "" FORCE)
endif()