
#include <gtest/gtest.h>

#include "IgnoreWarning.h"
#include "lib2.h"

class AsanTests: public ::testing::Test
{
};

#ifdef __clang__
	#define ASSERT_DEATH_NO_WARNING(...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
		__START_IGNORING_WARNINGS__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
		__IGNORE_WARNING__("-Wused-but-marked-unused")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
		ASSERT_DEATH(__VA_ARGS__)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \
		__STOP_IGNORING_WARNINGS__
#else
	#define ASSERT_DEATH_NO_WARNING ASSERT_DEATH
#endif

TEST_F(AsanTests, HeapUseAfterFree)
{
	lib2::ThisViolatesAsanChecks thisViolatesAsanChecks;
	ASSERT_DEATH_NO_WARNING(thisViolatesAsanChecks.HeapUseAfterFree(), "heap-use-after-free");
}

TEST_F(AsanTests, StackUseAfterScope)
{
	lib2::ThisViolatesAsanChecks thisViolatesAsanChecks;
	ASSERT_DEATH_NO_WARNING(thisViolatesAsanChecks.StackUseAfterScope(), "stack-use-after-scope");
}

TEST_F(AsanTests, MemoryLeak)
{
	lib2::ThisViolatesAsanChecks thisViolatesAsanChecks;
	ASSERT_DEATH_NO_WARNING(thisViolatesAsanChecks.MemoryLeak(), "memory leaks");
}
