
#include <gtest/gtest.h>

#include "IgnoreWarning.h"
#include "lib1.h"

class StlDebugTests: public ::testing::Test
{
};

#ifdef __clang__
	#define ASSERT_DEATH_NO_WARNING(...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
		__START_IGNORING_WARNINGS__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
		__IGNORE_WARNING__("-Wused-but-marked-unused")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
		ASSERT_DEATH(__VA_ARGS__)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \
		__STOP_IGNORING_WARNINGS__
#else
	#define ASSERT_DEATH_NO_WARNING ASSERT_DEATH
#endif

TEST_F(StlDebugTests, IteratorSanity)
{
	lib1::ThisViolatesStlDebugChecks thisViolatesStlDebugChecks;
	ASSERT_DEATH_NO_WARNING(thisViolatesStlDebugChecks.IteratorSanity(), "compare iterators");
}

TEST_F(StlDebugTests, AccessOutOfBounds)
{
	lib1::ThisViolatesStlDebugChecks thisViolatesStlDebugChecks;
	ASSERT_DEATH_NO_WARNING(thisViolatesStlDebugChecks.AccessOutOfBounds(), "attempt to subscript");
}

TEST_F(StlDebugTests, SortWithNonReflexiveFunction)
{
	lib1::ThisViolatesStlDebugChecks thisViolatesStlDebugChecks;
	ASSERT_DEATH_NO_WARNING(thisViolatesStlDebugChecks.SortWithNonReflexiveFunction(), "irreflexive");
}
