
#include <gtest/gtest.h>

#include "IgnoreWarning.h"
#include "lib4.h"

class TsanTests: public ::testing::Test
{
};

#ifdef __clang__
	#define ASSERT_DEATH_NO_WARNING(...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
		__START_IGNORING_WARNINGS__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
		__IGNORE_WARNING__("-Wused-but-marked-unused")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
		ASSERT_DEATH(__VA_ARGS__)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \
		__STOP_IGNORING_WARNINGS__
#else
	#define ASSERT_DEATH_NO_WARNING ASSERT_DEATH
#endif

TEST_F(TsanTests, DataRace)
{
	lib4::ThisViolatesTsanChecks thisViolatesTsanChecks;
	ASSERT_DEATH_NO_WARNING(thisViolatesTsanChecks.DataRace(), "data race");
}

